# Generated by Django 3.1.5 on 2021-01-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sancharamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pictures')),
                ('desc', models.TextField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
