# Generated by Django 3.1.5 on 2021-01-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sancharamapp', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='head',
        ),
        migrations.AddField(
            model_name='blog',
            name='day',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
